[package]
name = "collections"
version = "0.0.0"
authors = ["Akshay Nair <phenax5@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
